[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' www.google-analytics.com ajax.googleapis.com pagead2.googlesyndication.com www.googletagmanager.com; style-src 'self' 'unsafe-inline' unpkg.com; img-src 'self' data:; connect-src 'self' https://www.googleapis.com https://www.google-analytics.com; frame-src 'self' https://googleads.g.doubleclick.net;"
