version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pathlight"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3za9rt0ng6a5"
s3_prefix = "pathlight"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
